### ISSUE TITLE
Initial schema and content

### ISSUE THREAD

**Issue by foolip** [w3c/browser-specs#1]
The background for this repo is in https://github.com/tidoust/reffy/issues/172.

The first would be to have the same content as https://github.com/tidoust/reffy/tree/master/src/specs, but likely in a slightly different form as the css/idl/other split isn't necessary for other consumers of the list.

The simplest starting point would be a JSON file containing an array of entries. At minimum each entry is a URL. Reffy also needs `css` and `idl` booleans, although those could possibly be derived. https://github.com/foolip/day-to-day also has some other stuff, easiest shown by example:
```json
  {
    "id": "css-scroll-anchoring",
    "name": "CSS Scroll Anchoring",
    "href": "https://drafts.csswg.org/css-scroll-anchoring/",
    "specrepo": "w3c/csswg-drafts",
    "specpath": "css-scroll-anchoring css-scroll-anchoring-1",
    "testpath": "css/css-scroll-anchoring css-scroll-anchoring"
  }
```

In order to not have to duplicate all information from specref, it might also be a good idea to include the specref ID.

@dontcallmedom could you push a first commit with w3c.json and any required files, so that we can use PRs to explore the initial state?

**Comment by foolip** [comment]
Some thoughts on infrastructure:
- Check all bot and human PRs with a JSON schema
- Make this an auto-published npm package so that it can be depended upon by node projects and pinned

**Comment by foolip** [comment]
As pointed out in https://github.com/tidoust/reffy/issues/172#issuecomment-557547892, we should also consider https://github.com/mdn/kumascript/blob/master/macros/SpecData.json.

@sideshowbarker I see you contributed there, is it used beyond MDN?

**Comment by tidoust** [comment]
@foolip Repo is no longer empty, I pushed a first commit.

Regarding:

> In order to not have to duplicate all information from specref, it might also be a good idea to include the specref ID.

In most cases, you can use [reverse lookup](https://github.com/tobie/specref/blob/master/README.md#reverse-lookup) to gather information from the URL.

Overall, I would restrict the information here to the bare minimum to ease maintenance. In most cases, a URL is probably enough. To be completed when there is no easy way to get from the URL to other interesting information on the spec (e.g. because we need some other info to query the W3C API or specref, or find the corresponding test folder in Web Platform Tests).

In any case, along with the list, we should document mechanisms that allow to gather additional information on the specification from the info present here. Something like:
- How to get to the related entry point in the W3C API, Specref
- How to get to the underlying GitHub repository
- If we list /TR/ URLs, how to get to the Editor's Draft (e.g. using the W3C API or Specref)
- If we list Editor's Drafts, how to get to the published version if it exists
- How to compute a canonical shortname that could be used to identify the spec (e.g. how to get to the right folder name or corresponding IDL export in Web Platform Tests).

The repo could also contain (node.js to start with) implementations of these mechanisms that other projects could make use of.

**Comment by foolip** [comment]
> The repo could also contain (node.js to start with) implementations of these mechanisms that other projects could make use of.

Good idea!

**Comment by foolip** [comment]
On /TR/ URLs vs. Editor's Drafts, Specref can go from one to the other a lot of the time, and I suspect the W3C API can too. But there are going to be times when the connection is missing, so whichever we pick one of the sets is likely going to be incomplete.

My preference would be to use Editor's Draft or "latest version" as the default URL, since that by definition always exists, while /TR/ "only" exists for most W3C specs.

@dontcallmedom @tidoust what do you think the bar for completeness of ED->TR URLs should be, how can we check if it'll be good enough?

**Comment by foolip** [comment]
I sent https://github.com/w3c/browser-specs/pull/2 with the bare minimum.

**Comment by sideshowbarker** [comment]
> As pointed out in [tidoust/reffy#172 (comment)](https://github.com/tidoust/reffy/issues/172#issuecomment-557547892), we should also consider https://github.com/mdn/kumascript/blob/master/macros/SpecData.json.
> 
> @sideshowbarker I see you contributed there, is it used beyond MDN?

It’s not used beyond MDN, as far as I know.

**Comment by dontcallmedom** [comment]
I've just stumbled upon another potential customer: the TypeScript and JavaScript lib generator https://github.com/microsoft/TSJS-lib-generator/blob/master/inputfiles/idlSources.json

(this particular project might (also?) benefit from using Reffy IDL bundle directly maybe https://github.com/microsoft/TSJS-lib-generator/blob/master/src/idlfetcher.ts )

**Comment by dontcallmedom** [comment]
(filed https://github.com/microsoft/TSJS-lib-generator/issues/816 on my latest remark)

**Comment by sideshowbarker** [comment]
https://github.com/w3c/mdn-spec-links/blob/master/SPECMAP.json is another source that may or may not be useful for this effort.

It’s just a listing of spec URLs mapped to file names — but what’s significant about the set of specs listed is that it’s the set of specs which are linked to in one or more *Specifications* tables in any MDN articles.

**Comment by foolip** [comment]
I think it's very fair to say this issue has been addressed now. @tidoust is there anything more you'd like to do before closing it?

**Comment by tidoust** [comment]
Nope, I'm closing the issue. We have an initial schema, an initial list, and are tracking needs for additional properties in separate issues, and the need to detect missing specs present in other projects in #50.
