### ISSUE TITLE
Tons of new specs

### ISSUE THREAD

**Issue by BenjaminAster** [w3c/browser-specs#1008]
I was working on my own browser spec collection for myself, using [w3c/groups](https://github.com/w3c/groups) as a starting point and manually adding lots of stuff, partially by looking at the interfaces in the window object in Chrome's JavaScript console &ndash; until I realized the existence of this repo and webref. This has the disadvantage of having wasted a lot of time, but also the advantage of being able to diff my spec list with yours and finding the differences.

Here are specs that I believe should be added to this repo:

- Topics API: https://patcg-individual-drafts.github.io/topics/
- Private Aggregation API: https://patcg-individual-drafts.github.io/private-aggregation-api/
- WebXR Marker Tracking Module: https://immersive-web.github.io/marker-tracking/
- WebXR Meshing API Level 1: https://immersive-web.github.io/real-world-geometry/webxrmeshing-1.html
- WebXR Plane Detection Module: https://immersive-web.github.io/real-world-geometry/plane-detection.html
- Capture all screens: https://screen-share.github.io/capture-all-screens/
- Audio Session: https://w3c.github.io/audio-session/
- execCommand: https://w3c.github.io/editing/docs/execCommand/
- Mathematical Markup Language (MathML) Version 4.0: https://w3c.github.io/mathml/
- Media Capture and Streams Extensions: https://w3c.github.io/mediacapture-extensions/
- The Capture-Handle Actions Mechanism: https://w3c.github.io/mediacapture-handle/actions/
- Media Source Extensions Byte Stream Format Registry: https://w3c.github.io/mse-byte-stream-format-registry/
- ISO BMFF Byte Stream Format: https://w3c.github.io/mse-byte-stream-format-isobmff/
- MPEG-2 TS Byte Stream Format: https://w3c.github.io/mse-byte-stream-format-mp2t/
- MPEG Audio Byte Stream Format: https://w3c.github.io/mse-byte-stream-format-mpeg-audio/
- WebM Byte Stream Format: https://w3c.github.io/mse-byte-stream-format-webm/
- Confinement with Origin Web Labels: https://w3c.github.io/webappsec-cowl/
- Suborigins: https://w3c.github.io/webappsec-suborigins/
- User Interface Security and the Visibility API: https://w3c.github.io/webappsec-uisecurity/
- WebRTC Extensions: https://w3c.github.io/webrtc-extensions/
- Provisional Identifiers for WebRTC's Statistics API: https://w3c.github.io/webrtc-provisional-stats/
- XML Entity Definitions for Characters: https://w3c.github.io/xml-entities/
- Model Loader API: https://webmachinelearning.github.io/model-loader/
- Accessibility Object Model: https://wicg.github.io/aom/spec/
- AOM ARIA reflection: https://wicg.github.io/aom/spec/aria-reflection.html
- Default semantic properties for Custom Elements: https://wicg.github.io/aom/spec/custom-element-semantics.html
- AOM Input Event Types: https://wicg.github.io/aom/spec/input-events.html
- Conditional Focus: https://wicg.github.io/conditional-focus/
- Handwriting Recognition API: https://wicg.github.io/handwriting-recognition/
- Multicapture: https://wicg.github.io/multicapture/
- No-Vary-Search: https://wicg.github.io/nav-speculation/no-vary-search.html
- Pending Beacon: https://wicg.github.io/pending-beacon/
- Visual Viewport API: https://wicg.github.io/visual-viewport/
- Web Smart Card API: https://wicg.github.io/web-smart-card/
- Subresource Loading with Web Bundles: https://wicg.github.io/webpackage/subresource-loading.html
- Web Packaging: https://wicg.github.io/webpackage/draft-yasskin-dispatch-web-packaging.html
- Signed HTTP Exchanges: https://wicg.github.io/webpackage/draft-yasskin-http-origin-signed-responses.html
- Signed HTTP Exchanges Implementation Checkpoints: https://wicg.github.io/webpackage/draft-yasskin-httpbis-origin-signed-exchanges-impl.html
- Web Bundles: https://wpack-wg.github.io/bundled-responses/draft-ietf-wpack-bundled-responses.html
- Import Attributes: https://tc39.es/proposal-import-attributes/
- Iframe credentialless: https://wicg.github.io/anonymous-iframe/
- Math Accessibility API Mappings 1.0: https://w3c.github.io/math-aam/
- Digital Publishing WAI-ARIA Module 1.1: https://w3c.github.io/dpub-aria/
- Digital Publishing Accessibility API Mappings 1.1: https://w3c.github.io/dpub-aam/
- Web Monetization: https://webmonetization.org/specification/
- Payment Method Encryption: https://w3c.github.io/webpayments-crypto/
- Web Payments HTTP Messages 1.0: https://w3c.github.io/webpayments-http-messages/
- Tokenized Card Payment: https://w3c.github.io/webpayments-methods-tokenization/
- QUIC API for Peer-to-peer Connections: https://w3c.github.io/p2p-webtransport/
- QUIC API for Client-to-Server Connections: https://w3c.github.io/p2p-webtransport/cs.html
- Object RTC (ORTC) API for WebRTC: https://draft.ortc.org/
- Web Bluetooth Scanning: https://webbluetoothcg.github.io/web-bluetooth/scanning.html
- The MerchantValidationEvent interface: https://w3c.github.io/merchant-validation/
- Managed Configuration API: https://wicg.github.io/WebApiDevice/managed_config/
- Device Attributes API: https://wicg.github.io/WebApiDevice/device_attributes/
- overscroll and scrollend events: https://wicg.github.io/overscroll-scrollend-events/

## Specs that might be too unofficial or unmaintained to be in browser-specs, or that don't technically match the criteria
- Color API: https://wicg.github.io/color-api/
- WebP Container Specification (implemented in all three browser engines!): https://developers.google.com/speed/webp/docs/riff_container
- WebP Lossless Bitstream: https://developers.google.com/speed/webp/docs/webp_lossless_bitstream_specification
- Controlled Frame API: https://chasephillips.github.io/controlled-frame/
- AV1 family of specs:
	- HDR10+ AV1 Metadata Handling: https://aomediacodec.github.io/av1-hdr10plus/
	- AV1 Codec ISO Media File Format Binding: https://aomediacodec.github.io/av1-isobmff/
	- AV1 Bitstream & Decoding Process: https://aomediacodec.github.io/av1-spec/
	- Carriage of AV1 in MPEG-2 TS: https://aomediacodec.github.io/av1-mpeg2-ts/
	- AV1 Image File Format (AVIF) (implemented in all three browser engines!): https://aomediacodec.github.io/av1-avif/
	- RTP Payload Format For AV1: https://aomediacodec.github.io/av1-rtp-spec/
- AOMedia Film Grain Synthesis 1 (AFGS1): https://aomediacodec.github.io/afgs1-spec/
- Sourcing In-band Media Resource Tracks from Media Containers into HTML: https://dev.w3.org/html5/html-sourcing-inband-tracks/
- CSS Toggles: https://tabatkins.github.io/css-toggle/
- CSS Stacking Context Module Level 1: https://tabatkins.github.io/specs/css-stacking-context-1/
- Permissions Registry: https://w3c.github.io/permissions-registry/
- COLR — Color Table: https://learn.microsoft.com/en-us/typography/opentype/otspec191alpha/colr
- SVG Streaming: https://svgwg.org/specs/streaming/
- SVG Markers: https://svgwg.org/specs/markers/
- Box Tree API Level 1: https://drafts.css-houdini.org/box-tree-api-1/
- APNG Specification (implemented in all three browser engines!): https://wiki.mozilla.org/APNG_Specification
- MediaStreamTrack Insertable Media Processing using Streams (unofficial draft with MediaStreamTrackGenerator): https://alvestrand.github.io/mediacapture-transform/chrome-96.html

## Specs that I think should be removed from browser-specs:
- Writing Promise-Using Specifications: https://www.w3.org/2001/tag/doc/promises-guide
- W3C Patent Policy: https://www.w3.org/Consortium/Patent-Policy/
- W3C Process Document: https://www.w3.org/Consortium/Process/
- A Method for Writing Testable Conformance Requirements: https://www.w3.org/TR/test-methodology/
- Document Object Model (DOM) Level 2 Style Specification (deprecated and superseded by other specs): https://www.w3.org/TR/DOM-Level-2-Style/
- Cascading Style Sheets Level 2 Revision 1 (CSS 2.1) Specification (superseded by [Cascading Style Sheets Level 2 Revision 2 (CSS 2.2) Specification](https://www.w3.org/TR/CSS22/)): https://www.w3.org/TR/CSS21/
- TC39 proposals that have now been merged into the official ECMAScript standard:
	- Change Array by copy: https://tc39.es/proposal-change-array-by-copy/
	- Proposal-array-find-from-last: https://tc39.es/proposal-array-find-from-last/
	- Symbol as WeakMap Keys Proposal: https://tc39.es/proposal-symbols-as-weakmap-keys/

## Various other things:
- There are currently two editor's drafts for SVG 2: SVG 2.1 at https://svgwg.org/svg2-draft/ and SVG 2.2 at https://svgwg.org/svg-next/. Should the nightly url for the SVG 2 spec be changed to the svg-next version?
- CSS Animation Worklet's spec url changed from https://drafts.css-houdini.org/css-animationworklet-1/ (without hyphen) to https://drafts.css-houdini.org/css-animation-worklet-1/ (with hyphen).
- The link for CSS Style Attributes has the level number missing (https://drafts.csswg.org/css-style-attr/ instead of https://drafts.csswg.org/css-style-attr-1/). Not very important, but should be fixed for consistency.
- The [Web Cryptography Working Group](https://www.w3.org/2012/webcrypto/) doesn't seem to exist any more, and the [Web Cryptography API](https://w3c.github.io/webcrypto/) mentions the [Web Application Security Working Group](https://www.w3.org/groups/wg/webappsec/) as the group behind it.

Could some W3C person please either add the specs and modifications themselves or give me the OK and tell me which specs *not* to add so I can make a PR myself?

**Comment by tidoust** [comment]
Many thanks for the list, @BenjaminAster! I'll need some time to review the list in detail (I don't think I'll have time in the next couple of weeks in particular). Initial thoughts below.

The scope of browser-specs has evolved over time, and continues to evolve, but the list of specs it contains is not meant to be exhaustive. Rather, roughly, the list of specs that have "enough traction" to be considered part of the web platform, or that people need for cross-referencing purpose. We tend not to add early proposals or specs flagged as unofficial.

Specs in browser-specs get crawled by [Reffy](https://github.com/w3c/reffy) to maintain [Webref](https://github.com/w3c/webref), which in turn gets used to maintain IDL extracts in Web Platform Tests, cross-reference databases in spec authoring tools, CSS grammar parts in MDN pages, etc. Before we add a spec, we tend to ask ourselves: why is the spec needed? In many cases, the answer is straightforward. In some cases, typically for proposals raised in Community Groups, that's a judgment call, and we try to integrate feedback from the consumers of the list that we're aware of. If you can tell us what you're trying to achieve with the list, we might better be able to take your perspective into account.

Specs that we identified and that, we feel, are in the "too early to add" category get added to the [`monitor.json`](https://github.com/w3c/browser-specs/blob/main/src/data/monitor.json) file, and reviewed every few months. Specs that, we believe, won't ever be added are listed in [`ignore.json`](https://github.com/w3c/browser-specs/blob/main/src/data/ignore.json). Some of the specs that you suggest adding to the list are in these files, e.g., WebXR Marker Tracking Module, Handwriting recognition, Web Smart Card API, Web Monetization, etc.

We also do not add specs that have been abandoned or got merged into some other spec, e.g., execCommand, Provisional Identifiers for WebRTC's Statistics API, Visual Viewport (merged into CSSOM View).

There remains a number of specs in your list that we missed, or that could perhaps be added to the list!

Quick comments on some of the specs that you'd like to see removed:
- Writing Promise-Using Specifications, W3C Patent Policy, W3C Process Document, A Method for Writing Testable Conformance Requirements are in the list for cross-referencing purpose. They do not have `"browser"` in their `"categories"` property to distinguish them from specs that are more directly targeted at browser implementation.
- Document Object Model (DOM) Level 2 Style Specification is also in the list for cross-referencing purpose (be that from also outdated specs). It has a `"standing": "discontinued"` property to clarify that it has been discontinued.
- The CSS working group tends to prefer references to CSS2.1 (a Recommendation) than to CSS2.2 (a Working Draft)

Quick comments on "Various other things":
- Where do you get the "2.1" and "2.2" from for SVG? I'm not clear that this concept exists in the SVG Working Group. I don't know yet what SVG Next is supposed to be.
- The URL of the Editor's Draft of the CSS Animation Worklet spec url has not yet been updated in the published version of the spec: https://www.w3.org/TR/css-animation-worklet-1/ That is the source of truth for browser-specs.
- The missing level for CSS Style Attributes is also because the published spec does not have one (groups are not always consistent with themselves ;)): https://www.w3.org/TR/css-style-attr/
- Similar for WebCrypto, the WebAppSec WG took over maintenance of the spec but has not yet published a new version of the spec: https://www.w3.org/TR/WebCryptoAPI/. This probably applies to other specs as well (Encrypted Media Extensions comes to mind).

**Comment by BenjaminAster** [comment]
Thanks! Sorry, I didn't catch a few things here, especially stuff like the two JSON files you mentioned, and the `"categories"` array. And since the repo description says it's about "specifications used to build web browsers", I thought maybe the documents like "Writing Promise-Using Specifications" are out of scope for this list.

My concrete use case is that I'm building basically something like a frontend for webref &ndash; an index and search engine for specs, CSS properties, JS interfaces & functions, HTML elements etc. And for that, I do want to have the bleeding-edge things like handwriting recognition, many of which are already implemented (experimentally) in Chromium, so that when I stumble across e.g. some JS interface in the wild or when I explicitly want to get to the definition of something (including experimental Chromium stuff), I can simply type it in there and be linked to the spec. But if they're not in scope for this repo, that's ok, I'll simply augment this list with some specs that I crawl myself.

- execCommand: The HTML spec explicitly [states](https://html.spec.whatwg.org/multipage/interaction.html#editing-apis) that the execCommand() method is defined in [[EXECCOMMAND]](https://w3c.github.io/editing/docs/execCommand/). Has it really been abandoned or merged into another spec?
- DOM Level 2 & CSS2.1: Ok, I understand. I'll exclude them in my project then.
- SVG: Sorry, I mixed the numbers here (probably confused with CSS2), the Readme for the [SVGWG repo](https://github.com/w3c/svgwg#readme) lists the svg2-draft version as "SVG 2" and the svg-next one as "SVG 2.1" (although the Readme hasn't been updated in five years). The svg-next version simply has some new stuff like the [`<mesh>`](https://svgwg.org/svg-next/shapes.html#MeshElement) element, but all of them don't have any actual browser implementation I thinks, so yeah, the nightly URL should probably stay as svg2-draft.
- Animation Worklet, Style Attributes & Crypto: Oh, ok, got you! So you're simply taking the "Editor's draft" URL and the WG that the TR spec links to.

**Comment by tidoust** [comment]
Here is a first split of the lists into lists of specs to consider, and lists of specs that browser-specs already handles one way or the other.

Specs that are not in any list and should be considered for inclusion somewhere:
- [ ] Private Aggregation API: https://patcg-individual-drafts.github.io/private-aggregation-api/
- [ ] WebXR Meshing API Level 1: https://immersive-web.github.io/real-world-geometry/webxrmeshing-1.html
- [ ] WebXR Plane Detection Module: https://immersive-web.github.io/real-world-geometry/plane-detection.html
- [ ] Capture all screens: https://screen-share.github.io/capture-all-screens/
- [ ] Audio Session: https://w3c.github.io/audio-session/
- [ ] Media Source Extensions Byte Stream Format Registry: https://w3c.github.io/mse-byte-stream-format-registry/
- [ ] ISO BMFF Byte Stream Format: https://w3c.github.io/mse-byte-stream-format-isobmff/
- [ ] MPEG-2 TS Byte Stream Format: https://w3c.github.io/mse-byte-stream-format-mp2t/
- [ ] MPEG Audio Byte Stream Format: https://w3c.github.io/mse-byte-stream-format-mpeg-audio/
- [ ] WebM Byte Stream Format: https://w3c.github.io/mse-byte-stream-format-webm/
- [ ] Model Loader API: https://webmachinelearning.github.io/model-loader/
- [ ] No-Vary-Search: https://wicg.github.io/nav-speculation/no-vary-search.html
- [ ] Subresource Loading with Web Bundles: https://wicg.github.io/webpackage/subresource-loading.html
- [ ] Web Packaging: https://wicg.github.io/webpackage/draft-yasskin-dispatch-web-packaging.html
- [ ] Signed HTTP Exchanges: https://wicg.github.io/webpackage/draft-yasskin-http-origin-signed-responses.html
- [ ] Signed HTTP Exchanges Implementation Checkpoints: https://wicg.github.io/webpackage/draft-yasskin-httpbis-origin-signed-exchanges-impl.html
- [ ] Web Bundles: https://wpack-wg.github.io/bundled-responses/draft-ietf-wpack-bundled-responses.html
- [ ] Import Attributes: https://tc39.es/proposal-import-attributes/
- [ ] Iframe credentialless: https://wicg.github.io/anonymous-iframe/
- [ ] Math Accessibility API Mappings 1.0: https://w3c.github.io/math-aam/
- [ ] Payment Method Encryption: https://w3c.github.io/webpayments-crypto/
- [ ] Tokenized Card Payment: https://w3c.github.io/webpayments-methods-tokenization/
- [ ] QUIC API for Peer-to-peer Connections: https://w3c.github.io/p2p-webtransport/
- [ ] QUIC API for Client-to-Server Connections: https://w3c.github.io/p2p-webtransport/cs.html
- [ ] Object RTC (ORTC) API for WebRTC: https://draft.ortc.org/
- [ ] Web Bluetooth Scanning: https://webbluetoothcg.github.io/web-bluetooth/scanning.html
- [ ] The MerchantValidationEvent interface: https://w3c.github.io/merchant-validation/
- [ ] Managed Configuration API: https://wicg.github.io/WebApiDevice/managed_config/
- [ ] Controlled Frame API: https://chasephillips.github.io/controlled-frame/
- [ ] HDR10+ AV1 Metadata Handling: https://aomediacodec.github.io/av1-hdr10plus/
- [ ] AV1 Codec ISO Media File Format Binding: https://aomediacodec.github.io/av1-isobmff/
- [ ] AV1 Bitstream & Decoding Process: https://aomediacodec.github.io/av1-spec/
- [ ] Carriage of AV1 in MPEG-2 TS: https://aomediacodec.github.io/av1-mpeg2-ts/
- [ ] AV1 Image File Format (AVIF) (implemented in all three browser engines!): https://aomediacodec.github.io/av1-avif/
- [ ] RTP Payload Format For AV1: https://aomediacodec.github.io/av1-rtp-spec/
- [ ] AOMedia Film Grain Synthesis 1 (AFGS1): https://aomediacodec.github.io/afgs1-spec/
- [ ] Sourcing In-band Media Resource Tracks from Media Containers into HTML: https://dev.w3.org/html5/html-sourcing-inband-tracks/
- [ ] CSS Toggles: https://tabatkins.github.io/css-toggle/
- [ ] CSS Stacking Context Module Level 1: https://tabatkins.github.io/specs/css-stacking-context-1/
- [ ] Permissions Registry: https://w3c.github.io/permissions-registry/


Ignored, typically because they are not targeted at browsers, but perhaps worth re-considering now that browser-specs is more open to specs that don't specifically target browsers:
- [ ] Mathematical Markup Language (MathML) Version 4.0: https://w3c.github.io/mathml/
- [ ] XML Entity Definitions for Characters: https://w3c.github.io/xml-entities/
- [ ] Digital Publishing WAI-ARIA Module 1.1: https://w3c.github.io/dpub-aria/
- [ ] Digital Publishing Accessibility API Mappings 1.1: https://w3c.github.io/dpub-aam/
- [ ] Web Payments HTTP Messages 1.0: https://w3c.github.io/webpayments-http-messages/


Need to mark as obsoleted by ECMAScript spec:
- [ ] Change Array by copy: https://tc39.es/proposal-change-array-by-copy/
- [ ] Proposal-array-find-from-last: https://tc39.es/proposal-array-find-from-last/
- [ ] Symbol as WeakMap Keys Proposal: https://tc39.es/proposal-symbols-as-weakmap-keys/


In the list already:
- Topics API: https://patcg-individual-drafts.github.io/topics/
- The Capture-Handle Actions Mechanism: https://w3c.github.io/mediacapture-handle/actions/
- overscroll and scrollend events: https://wicg.github.io/overscroll-scrollend-events/


In the monitor list for now for some reason. These specs get reviewed for inclusion every few months:
- WebXR Marker Tracking Module: https://immersive-web.github.io/marker-tracking/
- Media Capture and Streams Extensions: https://w3c.github.io/mediacapture-extensions/
- Suborigins: https://w3c.github.io/webappsec-suborigins/
- WebRTC Extensions: https://w3c.github.io/webrtc-extensions/
- Accessibility Object Model: https://wicg.github.io/aom/spec/
- AOM Input Event Types: https://wicg.github.io/aom/spec/input-events.html
- Handwriting Recognition API: https://wicg.github.io/handwriting-recognition/
- Multicapture: https://wicg.github.io/multicapture/
- Pending Beacon: https://wicg.github.io/pending-beacon/
- Web Smart Card API: https://wicg.github.io/web-smart-card/
- Web Monetization: https://webmonetization.org/specification/
- Device Attributes API: https://wicg.github.io/WebApiDevice/device_attributes/
- Color API: https://wicg.github.io/color-api/
- SVG Markers: https://svgwg.org/specs/markers/
- Box Tree API Level 1: https://drafts.css-houdini.org/box-tree-api-1/


Ignored on purpose (e.g., no longer worked on, not a real proposal, incorporated in another spec):
- execCommand: https://w3c.github.io/editing/docs/execCommand/
- Confinement with Origin Web Labels: https://w3c.github.io/webappsec-cowl/
- User Interface Security and the Visibility API: https://w3c.github.io/webappsec-uisecurity/
- Provisional Identifiers for WebRTC's Statistics API: https://w3c.github.io/webrtc-provisional-stats/
- AOM ARIA reflection: https://wicg.github.io/aom/spec/aria-reflection.html
- Default semantic properties for Custom Elements: https://wicg.github.io/aom/spec/custom-element-semantics.html
- Conditional Focus: https://wicg.github.io/conditional-focus/
- Visual Viewport API: https://wicg.github.io/visual-viewport/
- SVG Streaming: https://svgwg.org/specs/streaming/
- MediaStreamTrack Insertable Media Processing using Streams (unofficial draft with MediaStreamTrackGenerator): https://alvestrand.github.io/mediacapture-transform/chrome-96.html


Specs that don't follow a well-known format and cannot be added for now even if we wanted to:
- WebP Container Specification (implemented in all three browser engines!): https://developers.google.com/speed/webp/docs/riff_container
- WebP Lossless Bitstream: https://developers.google.com/speed/webp/docs/webp_lossless_bitstream_specification
- COLR — Color Table: https://learn.microsoft.com/en-us/typography/opentype/otspec191alpha/colr
- APNG Specification (implemented in all three browser engines!): https://wiki.mozilla.org/APNG_Specification (but note that the list has the newer [PNG spec](https://w3c.github.io/PNG-spec/))

**Comment by dontcallmedom** [comment]
My thoughts on some of the specs:
>     * [ ]  Model Loader API: https://webmachinelearning.github.io/model-loader/

I think work on this has stopped, so I don't think it's worth adding (but will double-check)

>     * [ ]  Payment Method Encryption: https://w3c.github.io/webpayments-crypto/
>     * [ ]  Tokenized Card Payment: https://w3c.github.io/webpayments-methods-tokenization/
>     * [ ]  The MerchantValidationEvent interface: https://w3c.github.io/merchant-validation/

I think these have been abandoned (the activity on the repos has been to mark them as "not exposed"; it may be worth getting them more explicitly marked as abandoned though)
 
> 
>     * [ ]  QUIC API for Peer-to-peer Connections: https://w3c.github.io/p2p-webtransport/
>     * [ ]  QUIC API for Client-to-Server Connections: https://w3c.github.io/p2p-webtransport/cs.html

Not sure how likely these would get implemented in the short term if at all.
 
>     * [ ]  Object RTC (ORTC) API for WebRTC: https://draft.ortc.org/

I think there is no expectation this will get implemented in browsers at this point.

> Ignored, typically because they are not targeted at browsers, but perhaps worth re-considering now that browser-specs is more open to specs that don't specifically target browsers:
> 
>     * [ ]  Mathematical Markup Language (MathML) Version 4.0: https://w3c.github.io/mathml/
>     * [ ]  XML Entity Definitions for Characters: https://w3c.github.io/xml-entities/
>     * [ ]  Digital Publishing WAI-ARIA Module 1.1: https://w3c.github.io/dpub-aria/
>     * [ ]  Digital Publishing Accessibility API Mappings 1.1: https://w3c.github.io/dpub-aam/

These make sense to me.
 
>     * [ ]  Web Payments HTTP Messages 1.0: https://w3c.github.io/webpayments-http-messages/

Another case of an abandoned Web Payment spec.

> Specs that don't follow a well-known format and cannot be added for now even if we wanted to:
> 
>     * WebP Container Specification (implemented in all three browser engines!): https://developers.google.com/speed/webp/docs/riff_container
> 
>     * WebP Lossless Bitstream: https://developers.google.com/speed/webp/docs/webp_lossless_bitstream_specification
> 
>     * COLR — Color Table: https://learn.microsoft.com/en-us/typography/opentype/otspec191alpha/colr
> 
>     * APNG Specification (implemented in all three browser engines!): https://wiki.mozilla.org/APNG_Specification (but note that the list has the newer [PNG spec](https://w3c.github.io/PNG-spec/))

FWIW, each of these are referenced by an existing spec in web-specs (epub33 for WebP, css-fonts-4 for COLR, and HTML for APNG).

**Comment by BenjaminAster** [comment]
@tidoust Thanks for looking into the specs! Some time has passed since my original comment; here are a few things I want to add or comment on:

- [**execCommand**](https://w3c.github.io/editing/docs/execCommand/): As mentioned in my [second comment](https://github.com/w3c/browser-specs/issues/1008#issuecomment-1635612008), I'm not convinced that execCommand should be excluded from browser-specs. I know it's an extremely incompatible mess, and the spec is in early unofficial draft status etc., but it's referenced by the HTML spec, and if you were to build a new browser today, you would have to follow the spec in order to be web compatible.
- [**MathML 4**](https://w3c.github.io/mathml/): Many things from MathML that are not in MathML-Core are implemented in Firefox or WebKit.
- [**XML**](https://www.w3.org/TR/xml11/), [**XML Namespaces**](https://www.w3.org/TR/xml-names11/), [**XPath**](https://www.w3.org/TR/xpath-31/) & [**XSLT**](https://www.w3.org/TR/xslt-30/): I guess it's intentional they are left out since historically, they were not meant primarily for browsers? All browsers do support these, and they are required for the de facto web to function (SVG, XHTML, `DOMParser`, `XSLTProcessor`, `document.evaluate()`, etc.).
- [**Web Environment Integrity**](https://rupertbenwiser.github.io/Web-Environment-Integrity/)? New, unofficial and very controversial spec that is being implemented in Chromium. See also [chromestatus.com/feature/5796524191121408](https://chromestatus.com/feature/5796524191121408) and [en.wikipedia.org/wiki/Web_Environment_Integrity](https://en.wikipedia.org/wiki/Web_Environment_Integrity).
- [**GLSL**](https://registry.khronos.org/OpenGL/specs/es/3.2/GLSL_ES_Specification_3.20.html): Shading language for WebGL.
- [**glTF**](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html): File format for 3D models. AFAIK this is implemented in WebKit for the [&lt;model&gt;](https://immersive-web.github.io/model-element/) element.
- **Source Map**: The TC39 is working on a new official sourcemap spec that should replace the old [Google Doc](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/preview) and [sourcemaps.info](https://sourcemaps.info/spec.html): https://tc39.es/source-map-spec/.
- **Media formats?** Various more image, video, audio, font, etc. formats are not in browser-specs. Should they be added or is this out of scope? Or is it that you would but can't add them like with WebP?
- [**Close Watcher**](https://wicg.github.io/close-watcher/): Site doesn't exist anymore as a WICG spec and instead just links to https://github.com/whatwg/html/pull/9462.

**Comment by tidoust** [comment]
> * [**execCommand**](https://w3c.github.io/editing/docs/execCommand/): As mentioned in my [second comment](https://github.com/w3c/browser-specs/issues/1008#issuecomment-1635612008), I'm not convinced that execCommand should be excluded from browser-specs. I know it's an extremely incompatible mess, and the spec is in early unofficial draft status etc., but it's referenced by the HTML spec, and if you were to build a new browser today, you would have to follow the spec in order to be web compatible.

The [spec selection criteria](https://github.com/w3c/browser-specs/#spec-selection-criteria) that we try to follow are arguably fuzzy but start with "The spec is stable or in development". I would prefer things to be in a better shape but, for better or worse, execCommand is neither stable nor in development. The spec itself starts with "This spec is incomplete and it is not expected that it will advance beyond draft status. [...] The features described in this document are not implemented consistently or fully by user agents, and it is not expected that this will change in the foreseeable future".

> * [**MathML 4**](https://w3c.github.io/mathml/): Many things from MathML that are not in MathML-Core are implemented in Firefox or WebKit.

Adding MathML to the list makes sense, although I would add it without "browser" in its "categories" property. MathML-Core is supposed to represent the interoperable subset of MathML implemented in browsers. If there are many things implemented in browsers from MathML that are not in MathML-Core, the best would be to report them in the [MathML-Core repository](https://github.com/w3c/mathml-core/issues).

> * [**XML**](https://www.w3.org/TR/xml11/), [**XML Namespaces**](https://www.w3.org/TR/xml-names11/), [**XPath**](https://www.w3.org/TR/xpath-31/) & [**XSLT**](https://www.w3.org/TR/xslt-30/): I guess it's intentional they are left out since historically, they were not meant primarily for browsers? All browsers do support these, and they are required for the de facto web to function (SVG, XHTML, `DOMParser`, `XSLTProcessor`, `document.evaluate()`, etc.).

Ah, I would tell the history the other way round ;) They were meant for browsers, got implemented, but browser implementations stalled at version 1.0, while XPath and XSLT evolved to version 3.1. In other words, the latest versions are not what ships in browsers. I need to think some more on how to represent these specs in the list.

> * [**Web Environment Integrity**](https://rupertbenwiser.github.io/Web-Environment-Integrity/)? New, unofficial and very controversial spec that is being implemented in Chromium. See also [chromestatus.com/feature/5796524191121408](https://chromestatus.com/feature/5796524191121408) and [en.wikipedia.org/wiki/Web_Environment_Integrity](https://en.wikipedia.org/wiki/Web_Environment_Integrity).

One of the spec selection criteria is "The spec is being developed by a well-known standardization or pre-standardization group". This is meant to avoid spending time listing specs proposed by individuals until they have at least started their journey on the standardisation road.

Also the Chrome Status page says "No active development", which should signal that this proposal is *not* currently being implemented in Chromium. 
 
> * **Source Map**: The TC39 is working on a new official sourcemap spec that should replace the old [Google Doc](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/preview) and [sourcemaps.info](https://sourcemaps.info/spec.html): https://tc39.es/source-map-spec/.

To be considered. We usually add TC39 proposals when they reach stage 3. The Source Map spec says it is at stage 0.

> * [**GLSL**](https://registry.khronos.org/OpenGL/specs/es/3.2/GLSL_ES_Specification_3.20.html): Shading language for WebGL.
> * [**glTF**](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html): File format for 3D models. AFAIK this is implemented in WebKit for the [<model>](https://immersive-web.github.io/model-element/) element.
> * **Media formats?** Various more image, video, audio, font, etc. formats are not in browser-specs. Should they be added or is this out of scope? Or is it that you would but can't add them like with WebP?

That extends the scope a bit, but it would make sense overall. We're currently indeed somewhat stuck because the code won't know how to extract meaningful info from these specs, as they follow a different structure (some of them likely don't have an HTML representation either).

Side note: the `<model>` element is a bit like `<img>` and could be used to render models in glTF, USD, etc. I believe that the current early implementation in WebKit only supports USD for now though.

**Comment by BenjaminAster** [comment]
The WICG also just published a new draft specification "Web Preferences API": https://wicg.github.io/web-preferences-api/.

**Comment by tidoust** [comment]
> The WICG also just published a new draft specification "Web Preferences API": https://wicg.github.io/web-preferences-api/.

Thanks! For info, a job runs weekly to report new specs developed in well-known groups (see for instance #1044 for this week's report). Job can miss proposals, especially when they appear among others in a single repository. It should report that proposal next time it runs.

**Comment by tidoust** [comment]
Most of the specs listed in this issue have now been added to the main list, the monitoring list or the ignore list. I created follow-up issues to deal with the remaining (which require a bit more investigation or code changes): #1087, #1088, #1089.

I'm closing this issue as a result. Feel free to raise additional issues if you feel that we should revisit some of choices we made. And thanks again for the input, @BenjaminAster!
