### ISSUE TITLE
Add Topics API draft spec?

### ISSUE THREAD

**Issue by chrisdavidmills** [w3c/browser-specs#1012]
I want to add MDN compat data for The Topics API (https://patcg-individual-drafts.github.io/topics). would it be appropriate to add it to this repo?

**Comment by tidoust** [comment]
The Topics API is not yet in the list, partly due to the lack of multi-stakeholder buy-in for the proposal, and partly because it is still portrayed as an "individual draft proposal":

> This space is admistered by the PATCG and is a space to work on and discuss individual draft proposals that have not been adopted or approved by PATCG
> https://github.com/patcg-individual-drafts

If you need it, I guess we can still add it with a `"standing": "pending"` property. With that property, it's probably also ok to associate the spec with the PATCG group, even though, by definition, the group has not yet adopted the spec.

**Comment by chrisdavidmills** [comment]
> If you need it, I guess we can still add it with a `"standing": "pending"` property. With that property, it's probably also ok to associate the spec with the PATCG group, even though, by definition, the group has not yet adopted the spec.

That would be agreeable with me. I think you are still able to list a feature as non-standard while still linking to a spec, for cases like this, which is basically what this would be for now.

**Comment by tidoust** [comment]
Done! Latest versions of NPM packages include the Topics API.

**Comment by chrisdavidmills** [comment]
Lovely, thank you @tidoust!
