### ISSUE TITLE
Add execCommand spec?

### ISSUE THREAD

**Issue by Elchi3** [w3c/browser-specs#1429]
I see there is currently this entry for execCommand:

```
"https://w3c.github.io/editing/docs/execCommand/": {
"lastreviewed": "2024-03-01",
"comment": "no longer worked on and not implemented consistently or fully by user agents"
},
```

BCD/MDN would like to reference the spec for https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand at: https://w3c.github.io/editing/docs/execCommand/#dom-document-execcommand

https://github.com/w3c/trusted-types/issues/500#issuecomment-2044588710 says "https://w3c.github.io/editing/docs/execCommand/ is a bit dramatic about its status. It definitely needs to continue to be maintained." 

Should this be added? Thoughts?

**Comment by tidoust** [comment]
Adding links to past discussions on the topic:
- https://github.com/w3c/browser-specs/issues/58#issuecomment-636017113
- https://github.com/w3c/browser-specs/issues/1008#issuecomment-1700538283

Since then (or in parallel):
- The spec was added as a potential deliverable to the new [Web Editing WG charter](https://www.w3.org/2023/09/webediting-charter-2023.html#ig-other-deliverables)
- The Trusted Types thread suggests that @zcorpan will take over editing.

It would be great if there were some clearer signal in the spec itself that its maintenance has resumed.

**Comment by tidoust** [comment]
Closing as the execCommand spec was added to the list. The spec was added with a "pending" [standing](https://github.com/w3c/browser-specs/?tab=readme-ov-file#standing), pending proper adoption in the Web Editing WG and initial updates to the spec to note that it is no longer an "unofficial draft".
