### ISSUE TITLE
List pages for multi-page specs

### ISSUE THREAD

**Issue by tidoust** [w3c/browser-specs#15]
See discussion in https://github.com/w3c/browser-specs/issues/5#issue-567897765.

On top of storing whether the spec is single-page or multi-page, it would seem actually useful to expose the actual list of pages, because page extraction rules may vary from spec to spec.

In practice, multi-page specs to consider are typically:
- [HTML](html.spec.whatwg.org/multipage/)
- [CSS 2.2](https://drafts.csswg.org/css2/)
- [SVG 2](https://svgwg.org/svg2-draft/)

**Comment by tidoust** [comment]
> On top of storing whether the spec is single-page or multi-page, it would seem actually useful to expose the actual list of pages, because page extraction rules may vary from spec to spec.

Having run tests on all specs of interest, I note that the above statement is actually wrong. The code below can be run on index pages of all specifications to extract the list of pages. It is fairly straightforward and returns an empty array for single-page specs, and the list of page URLs for multi-page specs.

```js
function extractPages() {
  const allPages = [...document.querySelectorAll('.toc a[href]')]
    .map(link => link.href)
    .map(url => url.split('#')[0])
    .filter(url => url !== window.location.href);
  const pageSet = new Set(allPages);
  return [...pageSet];
}
```

In short, there is a priori no need to manually identify multi-page specs in `specs.json`.

Also, exposing the actual list of pages no longer strikes me as such a good idea in practice: if you're going to load and process specifications, you could just as well identify the pages when you load the index page. You'd be sure to use an up-to-date list of pages, and not a list that was assembled a few hours ago at best (granted, the list of pages is fairly stable in practice).

Actually, do we really need to identify multi-page specs in the list that browser-specs will expose? Are there scenarios where one wants to know in advance whether the spec is single-page or multi-page? For instance, @tabatkins, you mentioned in #5 that "the db tooling goes and discovers the relevant pages if it's a multipage spec". Doesn't the db tooling load and parse index pages of all specifications in any case? If so, it can probably run the above function on these index pages to get what it needs.

**Comment by tabatkins** [comment]
I'm of the opinion that the less bespoke work needed to be done to get useful information out of this database, the better.  In particular, requiring any user of this data to go and fetch the actual spec and run a particular query over it, utilizing specialized DOM APIs, just to get the list of pages that are part of the spec, seems bad.  It wouldn't be nearly as easy for me to do that in Python, for example.

> Doesn't the db tooling load and parse index pages of all specifications in any case?

As a downstream consumer of this data, I don't do any parsing of specs myself; I do need to know whether something is multipage or single-page tho (for various linking purposes).

Ultimately, tho, this project is, as far as I'm aware, intended to be used as the canonical reference for what relevant specs exist and where they live, so we can base all our other references off of it and have a consistent view of what exists where.  Since this is storing, among other things, the URL of the specs, I think it makes sense to store *all* the relevant URLs for a spec, if it has multiple.

In particular:

> Also, exposing the actual list of pages no longer strikes me as such a good idea in practice: if you're going to load and process specifications, you could just as well identify the pages when you load the index page. You'd be sure to use an up-to-date list of pages, and not a list that was assembled a few hours ago at best (granted, the list of pages is fairly stable in practice).

I would be quite scared to see what happened when a multipage spec changed its set of pages, and multiple data sources independently and at different times discovered this and tried to adjust and reconcile amongst themselves.

Contrast with the simplicity of everyone just trusting the canonical list of page urls from this repo, and at worst either missing a newly-added page or 404ing against a newly-deleted page until this repo updated, but otherwise continuing to present a consistent set of per-page data.

**Comment by tidoust** [comment]
Understood. I'm dropping the milestone because that's no longer a requirement to use the list in Reffy, but we'll add the list of pages afterwards.

**Comment by tidoust** [comment]
Closing the issue as the index now includes the list of pages for known multipage specs (HTML, SVG, CSS)
