### ISSUE TITLE
Add new spec: Login Status API

### ISSUE THREAD

**Issue by Elchi3** [w3c/browser-specs#1608]
### URL

https://w3c-fedid.github.io/login-status/

### Rationale

The spec got broken out in https://github.com/w3c-fedid/FedCM/pull/642

In BCD we use:
https://w3c-fedid.github.io/FedCM/#dom-navigatorlogin-setstatus
and now we want to use:
https://w3c-fedid.github.io/login-status/#dom-navigatorlogin-setstatus

But that ED seems not present in browser-specs due to the TR still duplicating things?
https://github.com/w3c/browser-specs/blob/a3d23ab8e4e4b5e3a2b64b7ea4b4c44f450d1f1d/src/data/monitor.json#L417-L420

### Additional properties

```json
{}
```

**Comment by tidoust** [comment]
Yes, we postponed inclusion to avoid creating duplicate definitions for terms defined in the Login Status API (and sub-section of FedCM). Also, I thought code would also pick up the latest published version link from the Login Status API draft, which links to FedCM.

Now, the login status section was removed from the Editor's Draft of FedCM, which should be OK enough to avoid major cross-reference issues, and it turns out that the code does not trust the latest published version link in any case, so won't produce any incorrect `release` information. In other words, if you need it, it seems fine to add it.

@browser-specs-bot pr
