### ISSUE TITLE
Add a source file path for each spec?

### ISSUE THREAD

**Issue by saschanaz** [w3c/browser-specs#173]
[webidl-updater currently uses arbitrary heuristics](https://github.com/saschanaz/webidl-updater/blob/main/src/crawl-raw-source.js) to guess the file path to update. It could be very useful if there is an easier way to guess it without manually iterating each repository.

**Comment by dontcallmedom** [comment]
`index.json` provides that in `nightly.filename` - does it match what you would need?

**Comment by saschanaz** [comment]
I think that refers to the path of the generated HTML, but in my case I need paths for raw bikeshed/respec files. It's currently quite random and I couldn't find a good way to detect it consistently. It would be great if we at least could build a convention. 🤔

**Comment by dontcallmedom** [comment]
oh, you're right that this is about the published content, not (necessarily) the source content (in ReSpec case, they'll often be one and the same, but clearly that doesn't apply to bikeshed).

I know that there other places where that information would be useful (e.g. https://github.com/w3c/spec-prod/issues/14) so +1 on finding a way to track this

**Comment by tidoust** [comment]
Regarding "finding a way to track this" today, I guess @saschanaz found a way. It's full of exceptions to the rule, but then there isn't any obvious other way to do it for now.

The question is more: is it worth adding to browser-specs? Given that there are already two projects that would benefit for it, that seems to be the case, so let's do it...

As with other properties, it may be worth separating exceptions to the rules that are specific to a single spec, and that we could rather track through a manual property in `specs.json` from exceptions to the rules that are more rules since they apply to multiple specs. In any case, we should probably have a mechanism in place to let someone specify the source file manually in `specs.json`.

**Comment by dontcallmedom** [comment]
in rules vs exceptions, my take is that we should only encode rules that are likely to be re-used in future repos.

We can use heuristics to fill the initial data, without necessarily having to maintain these heuristics over time if they're unlikely to be re-used.

**Comment by dontcallmedom** [comment]
other use cases for the data:
* allow to monitor activity specifically on spec-work (vs all the other data that might be maintained in a given repo)
* automatically populate `.pr-preview.json` on repos where it's not available today
* maybe a stretch - allow the IPR checker to react only to changes in the repo that relates to the spec source (cf https://github.com/w3c/ash-nazg/issues/125)

**Comment by tidoust** [comment]
Relevant code in webidl-updater has moved to [find-source-path.js](https://github.com/saschanaz/webidl-updater/blob/main/src/find-source-path.js).
