### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by tidoust** [w3c/browser-specs#28]

**Comment by tidoust** [comment]
Started with an MIT license. Is it suitable for data or should we adopt another license? If so, which one? W3C Software and Document License? CC-BY (or CC0)?

**Comment by BigBlueHat** [comment]
👍 for CC0 for the data portion and MIT (or the W3C Software and Documentation License) for the code.

The CC-BY license sadly can cause issues with Apache License 2.0 projects (due to CC-BY's "Effective Technological Measures" section):
https://www.apache.org/legal/resolved.html#cc-by

CC0 causes issues for no one. 😄

**Comment by tidoust** [comment]
That would work for me. @foolip, any issue with CC0 for the exported data and MIT for the code?
