### ISSUE TITLE
Add https://w3c.github.io/manifest-app-info/

### ISSUE THREAD

**Issue by Elchi3** [w3c/browser-specs#283]
https://w3c.github.io/manifest-app-info/

**Comment by marcoscaceres** [comment]
This spec shouldn't be added.

**Comment by Elchi3** [comment]
@marcoscaceres What should we use instead?

cc @sideshowbarker re https://github.com/mdn/browser-compat-data/pull/9856

**Comment by marcoscaceres** [comment]
Depends... are you documenting things used by multiple engines or app stores?

**Comment by sideshowbarker** [comment]
They're already documented in MDN at https://developer.mozilla.org/en-US/docs/Web/Manifest/categories, etc. Should we remove those MDN articles? The features are also in BCD. Should we remove them from BCD? As long as they are in BCD and documented in MDN and have a spec where they're defined,b is there a reason why we wound not want to record the spec URL? If we record the spec URL, we need a corresponding spec in browser-specs.

**Comment by marcoscaceres** [comment]
I don't think we need to remove them - but it should be clear that they don't have multivendor support. Sorry, what's BCD again?

**Comment by sideshowbarker** [comment]
BCD is https://github.com/mdn/browser-compat-data — it’s the data source for all the Browser Compatibility tables in MDN.

So the data shown at https://developer.mozilla.org/en-US/docs/Web/Manifest/categories#browser_compatibility comes from https://github.com/mdn/browser-compat-data/blob/main/html/manifest/categories.json

> I don't think we need to remove them from MDN - but it should be clear that they don't have multivendor support.

Arguably, https://developer.mozilla.org/en-US/docs/Web/Manifest/categories#browser_compatibility makes that clear(ish) — it shows, at last, that feature is currently supported only in Chrome on Android.

Beyond that, we these days otherwise make a practice of not attempting to editorialize further about whether something is on a path toward multivendor support.

Vendors who have made an investment in implementing particular features to solve problems for developers would not be super happy about the prospect of MDN articles warning developers away from actually using the features — by having big red warning boxes telling developers, *“This is a single-vendor feature that other browsers have no plans to implement support for”* (or whatever). It seems better to just let the Browser Compatibility tables do the talking.

**Comment by dontcallmedom** [comment]
coming back to the issue at hand (whether or not add the spec to browser-specs), the fact that it has some browser-based implementation means it probably [qualifies for addition here](https://github.com/w3c/browser-specs/blob/master/README.md#spec-selection-criteria)

**Comment by marcoscaceres** [comment]
Right, as it doesn't actually export anything (or declare any WebIDL), it should be ok to include.

**Comment by tidoust** [comment]
Added to browser-specs and released in [v1.35.0](https://github.com/w3c/browser-specs/releases/tag/1.35.0)
