### ISSUE TITLE
Provide both ECMAScript specification URLs (single page & multi page)?

### ISSUE THREAD

**Issue by Elchi3** [w3c/browser-specs#301]
1.38.1 actually **replaced** the single page ECMAScript spec URL with the multi page version.
I was thinking it would maybe offer the multi page data in addition to the single page so that this wouldn't be a breaking change for data consumers necessarily.

Would it be possible to have both in the data?

See https://github.com/mdn/yari/pull/3893 for background.

**Comment by tidoust** [comment]
I don't have a mechanism to offer to have both URLs in browser-specs today.

I think @dontcallmedom and I discussed in the past the possibility to maintain a history of URL aliases for a spec to cover cases such as WICG specs moving to a W3C group, or specs switching to a new shortname. If we had something like that in place, it could also be used to list the single page version of a multi-page spec. These aliases could for instance be useful to alert people when they are not using the canonical URL of a spec.

We have managed to make do without such a mechanism until now. I'm not necessarily jumping on adding it now if we can avoid it, simply because maintaining these aliases adds a bit of manual work. But we may not be able to avoid it forever...

For multi-page specs, the link to the single-page spec could perhaps be automatically extracted from the multi-page version but these links don't seem to follow a common pattern.

A side benefit of having a single URL is that it forces us to push for documents of interest to get updated when they don't link to the right URL, e.g. to analyze links to well-known specs. If the plan in BCD is indeed to switch to the multi-page URL for ECMAScript, then it makes sense to update the URL in Yari as well. In a way, the fact that something breaks on your side if you don't make that update seems like a good (although certainly annoying) thing ;)

**Comment by Elchi3** [comment]
> maintain a history of URL aliases for a spec to cover cases such as WICG specs moving to a W3C group, or specs switching to a new shortname. If we had something like that in place, it could also be used to list the single page version of a multi-page spec. These aliases could for instance be useful to alert people when they are not using the canonical URL of a spec.

Thanks, this sounds interesting! Also not saying we need this now but it's a good thought. 

> In a way, the fact that something breaks on your side if you don't make that update seems like a good (although certainly annoying) thing ;)

Ha, yes, I think you are actually right on here :) I hadn't really fully thought about how the different data sets (BCD and browser-specs) update their data and maybe rely on each other. This change definitely forces me to think more about that.

I'm closing here but thanks for your thoughts!
