### ISSUE TITLE
Is "Efficient Script Yielding" a relevant spec?

### ISSUE THREAD

**Issue by Elchi3** [w3c/browser-specs#306]
https://w3c.github.io/setImmediate/

It appears in our dataset due to these pages:
https://developer.mozilla.org/en-US/docs/Web/API/Window/clearImmediate#specifications
https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate

Is it a relevant spec or should we avoid referencing it from MDN/BCD?

**Comment by dontcallmedom** [comment]
My sense is that the spec is no longer being worked on (its repo has in fact been archived), and is unlikely at this point to gain further implementation, so I don't think it should be added to browser-specs, and probably doesn't need to be referenced from MDN/BCD.

**Comment by Elchi3** [comment]
Thanks, removing references to it then 👍

**Comment by foolip** [comment]
@Elchi3 asked me to comment here since I think we should keep the links in https://github.com/mdn/browser-compat-data/pull/10746. The way I've been thinking about browser-specs so far is as a list of specs that browser implementers might want to look at, and I've used it in https://foolip.github.io/day-to-day/ as a way to take the temperate on spec development.

So I actually think it's fine that browser-specs has dropped this spec, it's not something browser vendors need to care about. MDN/BCD however documents things that web developers might want to care about and only removes things that have been removed for over two years. This is a mismatch.

Since the BCD entries in question are heading for eventual removal (after 2022-01-15, two years after the Edge 79 release) I think a reasonable solution is to just allow exceptions to the "must be in browser-specs" rule.
