### ISSUE TITLE
`nightly.sourcePath` for `tracking-dnt` is wrong

### ISSUE THREAD

**Issue by saschanaz** [w3c/browser-specs#367]
Currently it's `index.html` but it should be `drafts/tracking-dnt.html`.

**Comment by tidoust** [comment]
I was surprised that this had gone unnoticed since the code should only produce files that actually exist in the repository. It turns out that the `dnt` repository contains a boilerplate `index.html` root file. I created https://github.com/w3c/dnt/pull/107 to get rid of it. The path needs to be set explicitly in `specs.json` in any case, thanks for the fix!
