### ISSUE TITLE
Add Intl.NumberFormat V3 proposal?

### ISSUE THREAD

**Issue by Elchi3** [w3c/browser-specs#488]
It looks like `tc39.es/proposal-intl-numberformat-v3/out/numberformat/proposed.html` isn't a browser-spec right now, see

https://github.com/w3c/browser-specs/blob/a2b1f2813338bf258413df8540931f601a73f411/src/data/monitor.json#L285

We have a BCD PR which proposes to add these spec_urls for new NumberFormat features which ship in Safari 15.4, see https://github.com/mdn/browser-compat-data/pull/14786

The spec_urls are 
- https://tc39.es/proposal-intl-numberformat-v3/out/numberformat/proposed.html#sec-intl.numberformat.prototype.formatrange
- https://tc39.es/proposal-intl-numberformat-v3/out/numberformat/proposed.html#sec-intl.numberformat.prototype.formatrangetoparts
- https://tc39.es/proposal-intl-numberformat-v3/out/pluralrules/proposed.html#sec-intl.pluralrules.prototype.selectrange

Do you want to revisit adding this spec? If not, BCD will probably add this to our allowlist.

**Comment by tidoust** [comment]
No problem except we'll need to add one entry per spec.

That was done in #489 but the problem is these individual entries are not full specs, and don't strictly follow the exact same format as full proposals, meaning that the extracted title is wrong for the time being, e.g.: https://github.com/w3c/browser-specs/blob/68019a60a9a94ec373f364ba6a2466dd2dad93c1/index.json#L1786-L1813

I'll fix that before releasing a new version of browser-specs.
