### ISSUE TITLE
Consider scanning for missing specs

### ISSUE THREAD

**Issue by foolip** [w3c/browser-specs#50]
In a [check-missing-specs.js](https://github.com/foolip/day-to-day/blob/e894f3c28e8e8f538a36a9c909f515e758311e2d/build/check-missing-specs.js) script for another project I wrote some code to discover specs missing from my list. I'm going to abandon that, but some of these tricks might be useful for this project:
- Look for all repos in https://github.com/w3c and https://github.com/WICG
- Load `https://${org}.github.io/${repo.name}/` for each one
- If they load, consider them a candidate

However, assuming that https://github.com/w3c/validate-repos is being run regularly, then this alternative may be better:
- For each repo check `repo-type` in `w3c.json` for the spec-like types

My code didn't include it, but for WHATWG we now have https://github.com/whatwg/sg/blob/master/db.json as a centralized source of information, which could also be used to look for what's missing in w3c/browser-specs.

**Comment by tabatkins** [comment]
Related: I just did a diff between Shepherd's set of known spec urls and the urls from here, and got the following results:

```
92 Shepherd URLs not in W3C data:
* http://www.w3.org/TR/mixed-content/
* http://www.w3.org/TR/referrer-policy/
* https://dev.w3.org/webfonts/WOFF2/spec/
* https://drafts.css-houdini.org/box-tree-api-1/
* https://drafts.css-houdini.org/css-parser-api-1/
* https://drafts.css-houdini.org/scroll-customization-api-1/
* https://drafts.csswg.org/css-2007/
* https://drafts.csswg.org/css-2010/
* https://drafts.csswg.org/css-2015/
* https://drafts.csswg.org/css-2017/
* https://drafts.csswg.org/css-2018/
* https://drafts.csswg.org/css-2020/
* https://drafts.csswg.org/css-box-4/
* https://drafts.csswg.org/css-egg-1/
* https://drafts.csswg.org/css-mobile/
* https://drafts.csswg.org/css-page-template-1/
* https://drafts.csswg.org/css-preslev-1/
* https://drafts.csswg.org/css-print/
* https://drafts.csswg.org/css-shadow-parts-1/
* https://drafts.csswg.org/css-speech-1/
* https://drafts.csswg.org/css-template-1/
* https://drafts.csswg.org/css-tv-1/
* https://drafts.csswg.org/css-viewport-1/
* https://drafts.csswg.org/mediaqueries-3/
* https://drafts.fxtf.org/custom-1/
* https://drafts.fxtf.org/matrix/
* https://immersive-web.github.io/dom-overlays/
* https://immersive-web.github.io/layers/
* https://w3.org/TR/css-nav-1/
* https://w3.org/TR/css-overscroll-1/
* https://w3c.github.io/fingerprinting-guidance/
* https://w3c.github.io/webcrypto/
* https://wicg.github.io/feature-policy/
* https://wicg.github.io/sms-one-time-codes/
* https://www.w3.org/2001/tag/doc/promises-guide/
* https://www.w3.org/TR/CSS21/
* https://www.w3.org/TR/DOM-Level-2-Style/
* https://www.w3.org/TR/REC-CSS1/
* https://www.w3.org/TR/SVG11/
* https://www.w3.org/TR/compositing-1/
* https://www.w3.org/TR/css-2010/
* https://www.w3.org/TR/css-2015/
* https://www.w3.org/TR/css-2017/
* https://www.w3.org/TR/css-2018/
* https://www.w3.org/TR/css-2020/
* https://www.w3.org/TR/css-animation-api-1/
* https://www.w3.org/TR/css-beijing/
* https://www.w3.org/TR/css-box-4/
* https://www.w3.org/TR/css-device-adapt/
* https://www.w3.org/TR/css-font-loading-3/
* https://www.w3.org/TR/css-gcpm-3/
* https://www.w3.org/TR/css-line-grid-1/
* https://www.w3.org/TR/css-masking-1/
* https://www.w3.org/TR/css-mobile/
* https://www.w3.org/TR/css-namespaces-3/
* https://www.w3.org/TR/css-print/
* https://www.w3.org/TR/css-scoping-1/
* https://www.w3.org/TR/css-shapes-1/
* https://www.w3.org/TR/css-snappoints-1/
* https://www.w3.org/TR/css-style-attr/
* https://www.w3.org/TR/css-variables-1/
* https://www.w3.org/TR/css-will-change-1/
* https://www.w3.org/TR/css3-align/
* https://www.w3.org/TR/css3-animations/
* https://www.w3.org/TR/css3-background/
* https://www.w3.org/TR/css3-color/
* https://www.w3.org/TR/css3-conditional/
* https://www.w3.org/TR/css3-exclusions/
* https://www.w3.org/TR/css3-images/
* https://www.w3.org/TR/css3-layout/
* https://www.w3.org/TR/css3-marquee/
* https://www.w3.org/TR/css3-mediaqueries/
* https://www.w3.org/TR/css3-multicol/
* https://www.w3.org/TR/css3-page/
* https://www.w3.org/TR/css3-positioning/
* https://www.w3.org/TR/css3-preslev/
* https://www.w3.org/TR/css3-regions/
* https://www.w3.org/TR/css3-selectors/
* https://www.w3.org/TR/css3-speech/
* https://www.w3.org/TR/css3-transitions/
* https://www.w3.org/TR/css3-ui/
* https://www.w3.org/TR/css4-images/
* https://www.w3.org/TR/cssom-1/
* https://www.w3.org/TR/cssom-view/
* https://www.w3.org/TR/hr-time-2/
* https://www.w3.org/TR/image-resource/
* https://www.w3.org/TR/json-ld11-api/
* https://www.w3.org/TR/matrix/
* https://www.w3.org/TR/selectors4/
* https://www.w3.org/TR/service-workers-1/
* https://www.w3.org/TR/svg2/
* https://www.w3.org/TR/worklets-1/
```

```
47 URLs that are just spelled differently between Shepherd and W3C:
* https://drafts.csswg.org/css-align-3/: https://drafts.csswg.org/css-align/
* https://drafts.csswg.org/css-animations-1/: https://drafts.csswg.org/css-animations/
* https://drafts.csswg.org/css-backgrounds-3/: https://drafts.csswg.org/css-backgrounds/
* https://drafts.csswg.org/css-backgrounds-4/: https://drafts.csswg.org/css-backgrounds/
* https://drafts.csswg.org/css-break-3/: https://drafts.csswg.org/css-break/
* https://drafts.csswg.org/css-cascade-4/: https://drafts.csswg.org/css-cascade/
* https://drafts.csswg.org/css-color-4/: https://drafts.csswg.org/css-color/
* https://drafts.csswg.org/css-contain-1/: https://drafts.csswg.org/css-contain/
* https://drafts.csswg.org/css-counter-styles-3/: https://drafts.csswg.org/css-counter-styles/
* https://drafts.csswg.org/css-device-adapt-1/: https://drafts.csswg.org/css-device-adapt/
* https://drafts.csswg.org/css-display-3/: https://drafts.csswg.org/css-display/
* https://drafts.csswg.org/css-easing-1/: https://drafts.csswg.org/css-easing/
* https://drafts.csswg.org/css-exclusions-1/: https://drafts.csswg.org/css-exclusions/
* https://drafts.csswg.org/css-font-loading-3/: https://drafts.csswg.org/css-font-loading/
* https://drafts.csswg.org/css-fonts-3/: https://drafts.csswg.org/css-fonts/
* https://drafts.csswg.org/css-gcpm-3/: https://drafts.csswg.org/css-gcpm/
* https://drafts.csswg.org/css-grid-1/: https://drafts.csswg.org/css-grid/
* https://drafts.csswg.org/css-line-grid-1/: https://drafts.csswg.org/css-line-grid/
* https://drafts.csswg.org/css-multicol-1/: https://drafts.csswg.org/css-multicol/
* https://drafts.csswg.org/css-namespaces-3/: https://drafts.csswg.org/css-namespaces/
* https://drafts.csswg.org/css-page-floats-3/: https://drafts.csswg.org/css-page-floats/
* https://drafts.csswg.org/css-position-3/: https://drafts.csswg.org/css-position/
* https://drafts.csswg.org/css-regions-1/: https://drafts.csswg.org/css-regions/
* https://drafts.csswg.org/css-rhythm-1/: https://drafts.csswg.org/css-rhythm/
* https://drafts.csswg.org/css-round-display-1/: https://drafts.csswg.org/css-round-display/
* https://drafts.csswg.org/css-scoping-1/: https://drafts.csswg.org/css-scoping/
* https://drafts.csswg.org/css-scroll-anchoring-1/: https://drafts.csswg.org/css-scroll-anchoring/
* https://drafts.csswg.org/css-scrollbars-1/: https://drafts.csswg.org/css-scrollbars/
* https://drafts.csswg.org/css-shapes-1/: https://drafts.csswg.org/css-shapes/
* https://drafts.csswg.org/css-style-attr-1/: https://drafts.csswg.org/css-style-attr/
* https://drafts.csswg.org/css-syntax-3/: https://drafts.csswg.org/css-syntax/
* https://drafts.csswg.org/css-transforms-1/: https://drafts.csswg.org/css-transforms/
* https://drafts.csswg.org/css-transitions-1/: https://drafts.csswg.org/css-transitions/
* https://drafts.csswg.org/css-ui-3/: https://drafts.csswg.org/css-ui/
* https://drafts.csswg.org/css-variables-1/: https://drafts.csswg.org/css-variables/
* https://drafts.csswg.org/css-will-change-1/: https://drafts.csswg.org/css-will-change/
* https://drafts.csswg.org/cssom-1/: https://drafts.csswg.org/cssom/
* https://drafts.csswg.org/cssom-view-1/: https://drafts.csswg.org/cssom-view/
* https://drafts.csswg.org/resize-observer-1/: https://drafts.csswg.org/resize-observer/
* https://drafts.csswg.org/selectors-4/: https://drafts.csswg.org/selectors/
* https://drafts.csswg.org/selectors-nonelement-1/: https://drafts.csswg.org/selectors-nonelement/
* https://drafts.fxtf.org/fill-stroke-3/: https://drafts.fxtf.org/fill-stroke/
* https://drafts.fxtf.org/geometry-1/: https://drafts.fxtf.org/geometry/
* https://www.w3.org/TR/WebIDL/: https://www.w3.org/TR/WebIDL-1/
* https://www.w3.org/TR/navigation-timing/: https://www.w3.org/TR/navigation-timing-2/
* https://www.w3.org/TR/network-error-logging/: https://www.w3.org/TR/network-error-logging-1/
* https://www.w3.org/TR/webauthn/: https://www.w3.org/TR/webauthn-2/
```

**Comment by tabatkins** [comment]
* There's a chunk of CSS specs that just have old-style URLs in Shepherd, and need updating on Shepherd's end. That's an easy fix.

* There's a big set where the W3C data for a spec (which is always versioned) points to an (unversioned) nightly url, which is incorrect. That needs fixing; the unversioned drafts URLs update to newer versions as they're published. (We include the unversioned URL in the spec metadata purposefully, because we *don't want* readers of the spec to go to old EDs by default, but the correct versioned URL is required for links to work.) Unsure how best to fix this, tho.

* There's a small set of new specs that haven't gotten a TR publication at all, like sms-one-time-codes, or a number of newer CSS drafts. Those would be fixed by @foolip's suggested repo crawl, I think. (Immersive Web wouldn't be caught by that, tho.)  Perhaps we can guide the crawl with a datafile like what's used by [bikeshed-tests](https://github.com/foolip/bikeshed-tests)? (Lets you add orgs, repos, or individual files, and exclude things when necessary.)

* Finally, there's a big chunk of /TR specs that aren't showing up in the W3C data. Some of them, like HR Time, have a *newer* version in the W3C data (W3C has hr-time-3, Shepherd has hr-time-2), but some, like image-resource, just don't exist at all. Not sure what's up with that.

**Comment by plinss** [comment]
> There's a chunk of CSS specs that just have old-style URLs in Shepherd, and need updating on Shepherd's end. That's an easy fix.

Not sure what you mean about 'old-style', the main difference I see is that Shepherd has versioned URLs, which it needs. It figures which one the unversioned url refers to by the 'current_version' field.

**Comment by tabatkins** [comment]
I'm talking about all the urls in the list that are `css3-foo`, when /TR has redirects to the `css-foo-3` name now.

**Comment by plinss** [comment]
Got it. I'll write a quick script to run through Shepherd's URLs and look for redirects, then update the DB.

**Comment by plinss** [comment]
And done.

**Comment by tidoust** [comment]
@tabatkins I suspect that you compared the URL in Shepherd with `release.url`. I note that there is a chunk of URLs for which W3C systems still return an `http` URL. That explains why you could not find some of the specs. I'll see if that can be fixed. I see @foolip just filed that under #55.

**Comment by foolip** [comment]
Some specific missing specs listed in https://github.com/w3c/browser-specs/issues/58.

**Comment by tabatkins** [comment]
I just grabbed both release and nightly urls from each entry, and compared them with Shepherd's "current" and "dated" urls.  I also autocorrect http to https automatically, because I did see that showing a few problems earlier.

**Comment by foolip** [comment]
For https://github.com/w3c/csswg-drafts, to discover new things we'd just look at what directories exists, says @tabatkins.

**Comment by foolip** [comment]
We can also look in https://github.com/tabatkins/bikeshed/tree/master/tests/github to find things that are probably tests.

**Comment by dontcallmedom** [comment]
Running a comparison with the content of [Sheperd spec endpoint](https://api.csswg.org/shepherd/spec/) based on `base_uri`, falling back on `draft_uri`, I find the following diff, split into categories of reasoning for the diff:

To be evaluated for addition in browser-specs:
- [ ] https://drafts.css-houdini.org/box-tree-api-1/
- [ ] https://drafts.csswg.org/css-forms-1/
- [ ] https://drafts.csswg.org/css-page-template-1/

Non normative documents (so probably not in scope for browser-specs):
- [ ] https://www.w3.org/TR/css-beijing/
- [ ] https://www.w3.org/TR/css-2010/
- [ ] https://www.w3.org/TR/css-2015/
- [ ] https://www.w3.org/TR/css-2017/
- [ ] https://www.w3.org/TR/css-2018/
- [ ] https://www.w3.org/TR/css-2020/
- [ ] https://drafts.csswg.org/css-egg-1/
- [ ] https://w3c.github.io/fingerprinting-guidance/
- [ ] https://www.w3.org/2001/tag/doc/promises-guide/

Not for browser implementations (so probably not in scope for browser-specs):
- [ ] https://www.w3.org/TR/json-ld11-api/


Bug in Shepherd data:
- [ ] https://www.w3.org/TR/css-animation-api-1/ (instead of css-animation-worklet-1)
- [ ] https://drafts.csswg.org/css-page-floats-3/ (missing TR url in `base_uri`)
- [ ] https://drafts.css-houdini.org/css-parser-api-1/ (this has moved to https://wicg.github.io/css-parser-api/)
- [ ] https://wicg.github.io/feature-policy/ (moved to https://w3c.github.io/webappsec-feature-policy/ )
- [ ] https://drafts.csswg.org/css-viewport-1/ (404)
- [ ] https://drafts.css-houdini.org/scroll-customization-api-1/ (not a spec - or is it a feature?
- [ ] (I'm not sure if the few http: URIs listed at the bottom of this are as expected or not)

Retired or not latest specs:
- [ ] https://www.w3.org/TR/css-device-adapt/
- [ ] https://www.w3.org/TR/css3-marquee/
- [ ] https://www.w3.org/TR/css-mobile/
- [ ] https://www.w3.org/TR/css3-preslev/
- [ ] https://www.w3.org/TR/css-print/
- [ ] https://www.w3.org/TR/css-tv/
- [ ] https://www.w3.org/TR/REC-CSS1/
- [ ] https://www.w3.org/TR/CSS21/
- [ ] https://www.w3.org/TR/DOM-Level-2-Style/
- [ ] https://www.w3.org/TR/css3-layout/
- [ ] https://drafts.fxtf.org/custom-1/
- [ ] https://www.w3.org/TR/hr-time-2/ (hr-time-3 is out)
- [ ] https://www.w3.org/TR/matrix/
- [ ] https://www.w3.org/TR/SVG11/ (browser-specs consider only SVG2)
- [ ] https://www.w3.org/TR/webauthn/ (webauthn-2 is out)


Tracked under a different name:
- [ ] https://www.w3.org/TR/cssom-view/ vs https://www.w3.org/TR/cssom-view-1/
- [ ] https://www.w3.org/TR/WebIDL/ vs  https://www.w3.org/TR/WebIDL-1/
- [ ] https://www.w3.org/TR/navigation-timing/ vs https://www.w3.org/TR/navigation-timing-2/
- [ ] https://www.w3.org/TR/network-error-logging/ vs https://www.w3.org/TR/network-error-logging-1/
- [ ] http://www.w3.org/TR/mixed-content/ (`http` vs `https`)
- [ ] http://www.w3.org/TR/referrer-policy/ (`http` vs `https`)
- [ ] http://www.w3.org/TR/SRI/ (`http` vs `https`)
- [ ] http://www.w3.org/TR/upgrade-insecure-requests/ (`http` vs `https`)

**Comment by dontcallmedom** [comment]
> For https://github.com/w3c/csswg-drafts, to discover new things we'd just look at what directories exists, says @tabatkins.

#106 does this

**Comment by dontcallmedom** [comment]
@tabatkins @plinss can you comment (or direct me to the right place to raise the question) on whether the following documents will ever evolve toward real specs, or if we can safely ignore them here?
* https://drafts.csswg.org/web-animations-css-integration/
* https://drafts.csswg.org/css-page-template-1/

**Comment by dontcallmedom** [comment]
#125 shows we have a workable system to track new specs, so closing this issue

**Comment by foolip** [comment]
Excellent, thanks @dontcallmedom and @tidoust!
