### ISSUE TITLE
Support `fork` as a composition model?

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/browser-specs#511]
#508 seems to indicate a composition model where a core spec is forked into new repos to integrate extensions to it.

Assuming this is a pattern that we want to support, maybe we could add a new `fork` value to the seriesComposition (in addition to `delta`), which would result in the data extracted from these forked specs to be re-based as being on top of the core spec to avoid duplicate `<dfn>`, IDL fragments, etc. I'm not entirely sure how we would achieve this robustly.

(since `<dfn>` extraction isn't a thing yet for WASM per https://github.com/w3c/reffy/issues/452, maybe this is "just" a matter of IDL-diffing for now?)

**Comment by tidoust** [comment]
> to be re-based as being on top of the core spec to avoid duplicate <dfn>, IDL fragments, etc. I'm not entirely sure how we would achieve this robustly.

I note I'm not sure either. If we want to be able to patch things, the logic to re-base things should run during the data curation phase in webref (as opposed to during the crawl in Reffy, as Reffy would not know how to deal with situations that require manual intervention).

More importantly, manual intervention seems almost inevitable. For instance, the Exception handling fork of WebAssembly extends the `ImportExportKind` enum to add a `"tag"` value. In delta specs, when that happens, we would patch the base spec to drop the enum definition from there so as to keep the "fullest" definition. But then there may be more than one fork of the same spec, each with their own possibly incompatible IDL extensions. What should the IDL extracts contain in such cases? What should the patches be?

In the short term, I propose to update Reffy so that it does **not** create IDL extracts for forks for now.

**Comment by tidoust** [comment]
Closing as fork specs are now supported. I created https://github.com/w3c/reffy/issues/901to track improvements in Reffy to handle CSS/IDL extracts for these specs.
