### ISSUE TITLE
Many HTTP URLs that could/should be HTTPS

### ISSUE THREAD

**Issue by foolip** [w3c/browser-specs#55]
These URLs appear in the dataset and could probably all be HTTPS:

http://dev.w3.org/csswg/css2/
http://dev.w3.org/csswg/css3-mediaqueries/
http://drafts.csswg.org/css-shadow-parts/
http://w3c.github.io/webrtc-priority/
http://webaudio.github.io/web-midi-api/
http://www.w3.org/TR/CSS2/
http://www.w3.org/TR/CSS22/
http://www.w3.org/TR/DOM-Parsing/
http://www.w3.org/TR/SRI/
http://www.w3.org/TR/battery-status/
http://www.w3.org/TR/compositing-1/
http://www.w3.org/TR/css-device-adapt-1/
http://www.w3.org/TR/css-font-loading-3/
http://www.w3.org/TR/css-gcpm-3/
http://www.w3.org/TR/css-line-grid-1/
http://www.w3.org/TR/css-masking-1/
http://www.w3.org/TR/css-namespaces-3/
http://www.w3.org/TR/css-page-floats-3/
http://www.w3.org/TR/css-regions-1/
http://www.w3.org/TR/css-scoping-1/
http://www.w3.org/TR/css-shapes-1/
http://www.w3.org/TR/css-style-attr/
http://www.w3.org/TR/css-variables-1/
http://www.w3.org/TR/css-will-change-1/
http://www.w3.org/TR/css3-conditional/
http://www.w3.org/TR/css3-exclusions/
http://www.w3.org/TR/css3-mediaqueries/
http://www.w3.org/TR/cssom-1/
http://www.w3.org/TR/cssom-view-1/
http://www.w3.org/TR/svg-markers/
http://www.w3.org/TR/svg-strokes/
http://www.w3.org/TR/touch-events/
http://www.w3.org/TR/upgrade-insecure-requests/
http://www.w3.org/TR/webmidi/
http://www.w3.org/TR/worklets-1/

**Comment by tidoust** [comment]
First few ones (those that target Editor's Drafts) have been fixed upstream in W3C systems and released in [v1.2.0](https://github.com/w3c/browser-specs/releases/tag/1.2.0).

The remaining ones cannot be fixed upstream today, because the same info is used to maintain the [tr.rdf](https://www.w3.org/2002/01/tr-automation/tr.rdf) file where the HTTP URL appears (because these specs have been published before we switched to HTTPS everywhere). Switching a URL from HTTP to HTTPS in RDF means that you're no longer talking about the same subject, which could break tools that make use of that info.

I don't think we're tied to the same strict rules here, so perhaps we can just force the switch to HTTPS when we retrieve the info from the W3C API.

**Comment by foolip** [comment]
Simply normalizing all URLs and changing the protocol to HTTPS would work, right?

**Comment by tidoust** [comment]
Right, I don't even think that we need to parse strings as URLs in practice. Replacing `http:` by `https:` at the beginning of the string should be all it takes.

**Comment by foolip** [comment]
That would do the trick, yeah :)

**Comment by tidoust** [comment]
All HTTP URLs returned by the W3C API are now automatically converted to HTTPS, and a test ensures that there is no HTTP URL in `index.json`.
