### ISSUE TITLE
Add editor's draft for Payment Method Manifest spec?

### ISSUE THREAD

**Issue by chrisdavidmills** [w3c/browser-specs#801]
Hi there,

Looking through the repo, you seem to have the first public working draft URL of this spec included: https://www.w3.org/TR/payment-method-manifest/

But I am trying to add data for this to MDN BCD at the moment, and it keeps giving me an invalid specification error. I wondered if it would work better if you included the latest editor's draft spec in the repo: https://w3c.github.io/payment-method-manifest/ ?

Thanks in advance!

**Comment by tidoust** [comment]
The canonical identifier for specs in browser-specs is always the most stable URL. For W3C specs published under /TR, that is the /TR URL because, per process, that URL should stand the test of time, as opposed to drafts under `github.io` that sometimes get moved to other organizations or repositories.

That said, https://w3c.github.io/payment-method-manifest/ does appear as the nightly URL of the Payment Method Manifest spec, under `nightly.url` (or `series.nightlyUrl`). I thought that was what BCD was using to link to the most recent draft of the spec. Isn't that the case?

**Comment by chrisdavidmills** [comment]
Hrm, that is really odd. It should have worked then. No matter. I'll leave this alone for now — I ended up abandoning the related work because since there are now multiple manifests to consider, we are thinking about how to restructure the BCD and MDN content to account for that. I'll return to it after that.

**Comment by tidoust** [comment]
Closing. Feel free to re-open or create another issue if you bump into this problem again.
