### ISSUE TITLE
css2 shouldn't request renaming

### ISSUE THREAD

**Issue by fantasai** [w3c/browser-specs#879]
Bikeshed is returning the following lint error:

> LINK ERROR: The spec 'css2' was renamed to 'css22'; please update your links.

I don't think this should be an error. I also have no idea where it comes from or how to fix it, but Tab pointed to this repo?

**Comment by tidoust** [comment]
Happy to update the data in browser-specs, but what do you expect `css2` to link to? CSS 2.1 or CSS 2.2?

- For Specref, [`css2`](https://www.specref.org/?q=css2) is an alias of CSS 2.1
- Under https://www.w3.org/TR/, [`css2`](https://www.w3.org/TR/CSS2/) is also an alias of CSS 2.1
- Under https://drafts.csswg.org/, [`css2`](https://drafts.csswg.org/css2/) returns the latest editor's draft, currently CSS 2.2

Data in browser-specs tends to align with /TR where possible, and avoid aliases.

**Comment by fantasai** [comment]
@tidoust Yes, please align with /TR and link it to /TR/CSS2

**Comment by tidoust** [comment]
The list now uses `css2` as the shortname for CSS 2.1. Data in Webref was updated accordingly and I believe already ingested by Bikeshed.

**Comment by fantasai** [comment]
I don't know what has happened, but Bikeshed is now failing to build links to CSS2.1 sub-pages, giving a lot of CSS specs fatal errors. CC @tabatkins @tidoust

**Comment by frivoal** [comment]
What I believe is happening is that `CSS2` is now aliased with `CSS22`, not `CSS21`, which is a problem because:
* CSS22 doesn't have CSS21's breakdown into chapters
* CSS22 doesn't have the same ids for headings as CSS21
Which means that `[[CSS2/visuren#anonymous]]` which would (and used to) resolve fine if it was against CSS21, doesn't resolve against CSS22, and can't be made to resolve by saying ``[[CSS2/#anonymous]]` as that anchor isn't the right one for that heading.

**Comment by frivoal** [comment]
> What I believe is happening is that CSS2 is now aliased with CSS22, not CSS21,

Actually, that's probably not quite it, because `[[CSS2]]` does link to CSS21.

I don't really know if we're discussing this in the right place, or if it should move to bikeshed, but either way, this needs solving :)

**Comment by tabatkins** [comment]
If we're changing (or already have changed?) the name of css2 in WebRef data, I'll have to fix the Bikeshed nit that complains about using `css2` and suggests `css22` instead.

**Comment by frivoal** [comment]
Not sure about that @tabatkins. In theory, yes, because CSS21 has known errors which CSS22 is supposed to be fixing, but CSS22 is largely unmaintained, and has been a somewhat incoherent state ever since we reverted the overly enthusiastic edits that had been made to it. So while it should be a better target than CSS21, I am not sure it actually is.

**Comment by fantasai** [comment]
@dontcallmedom Filed the issue for you, but the problem here isn't automatic terminology cross-linking, we're linking to specific headings and getting errors here.

**Comment by dontcallmedom** [comment]
ah, important clarification indeed! The relevant data file is then https://github.com/w3c/webref/blob/main/ed/headings/CSS2.json which shows that reffy is only indexing headings in the overview and changes pages - so definitely a bug somewhere; I'll try to investigate further tomorrow.

**Comment by tidoust** [comment]
Headings issue tracked in https://github.com/w3c/reffy/issues/1223. More a limitation of the crawler than a bug, the CSS 2.1 spec follows a different pattern for headings, through the use of `<a name>` anchors to create IDs, which the crawler does not support.
